### ISSUE TITLE
The new item cards are large on a desktop monitor

### ISSUE THREAD

**Issue by ThomasOwens** [kihashi/stardew_community_checklist#118]
The new item cards are incredibly wide, with what seems like an excessive amount of whitespace. In a fully maximized browser on desktop, I'm only getting two cards per row. That leaves a lot of scrolling down the page, which I do to get a good idea of what else is available in the current season. Before v2.0, there were three or 4 cards per row, which was far less vertical scrolling.

**Comment by kihashi** [comment]
Hey @ThomasOwens ,

Can you give me a little bit more info about your system? I'd like to know the monitor size and font scaling in particular, which you can get from display settings.

![image](https://user-images.githubusercontent.com/610242/54477406-dfd2f600-47dd-11e9-90d4-85d7661d9a91.png)

You should be seeing 4 cards per row on desktop.

< 768px will show 1 card
768-1023 will show 2 cards
1023-1215 will show 3 cards
> 1215 will show 4 cards

**Comment by ThomasOwens** [comment]
Absolutely.

![SDCC on Laptop Monitor](https://user-images.githubusercontent.com/35041/54480258-95ad3d00-47fc-11e9-8f25-b6ce298951c3.png)
![SDCC on External Monitor](https://user-images.githubusercontent.com/35041/54480259-95ad3d00-47fc-11e9-9292-f6345d7a9f33.png)

The top picture is the site on my laptop monitor. The bottom picture is the site on my external monitor, where it normally is when I'm playing SDV.

The laptop monitor has a scale of 125% and a resolution of 1920x1080. The external monitor has a scale factor of 100% and a resolution of 1600x900.

Based on what you said, I would expect to be seeing 4 cards per row on both screens, but that's not what I'm seeing.

Let me know if you'd like to see anything else. If I have some more time later, I may poke around in the code or in the Chrome dev tools to see if I can narrow down the problem, but I'm not that strong in front-end development and haven't touched Vue before, so I don't know how useful that would be.
