### ISSUE TITLE
Add Tooltips to Icons

### ISSUE THREAD

**Issue by Sempiternity87** [kihashi/stardew_community_checklist#147]
The season and skill icons are not easily understood at first glance. Adding a tooltip to them would be helpful to learn what each icon means, instead of guessing. It made more sense once I went to Search and saw all of them together. It could be more helpful to see these tooltips on the cards.

**Comment by kihashi** [comment]
@Sempiternity87 Thanks for your contribution! This was done in MR#105 and Issue #96 . It is not yet in the live version of the site, but will be included in v 2.1.

**Comment by Sempiternity87** [comment]
Got it. I did a search in the issues and didn't see anything, but I left the default filters :P.
