### ISSUE TITLE
'Hide Completed Bundles' filter

### ISSUE THREAD

**Issue by nitrohdev** [kihashi/stardew_community_checklist#44]
Similar to the "Hide Completed" filter, add another filter to hide all items from any bundle that is completed.

Example: I have 5/5 Completed for the Crab Pot bundle, but the other 5 items I don't need show up in the lists still as needed. I can mark all 10 as a workaround, but this would be a nice addition.

**Comment by kihashi** [comment]
That makes sense. It would be like "If the bundle is complete, hide all items from the bundle, else hide items marked as complete". When I added the "hide completed" toggle, I was really only thinking about the Bundles tab, but it isn't very helpful for the other tabs in its current state.
