### ISSUE TITLE
Incorrect counter for Vault Bundle

### ISSUE THREAD

**Issue by dimak** [kihashi/stardew_community_checklist#69]
Small change, data-only: vault bundles are each marked as having 5 slots per bundle.  That is incorrect--they only have 1 slot per bundle.  Because of this, the Vault tally shows a total of 20 bundle slots, instead of 4.

Great job, by the way, awesome tool.

**Comment by kihashi** [comment]
Thanks for the bug report! I actually noticed this a couple days ago when I completed my Vault bundle, but hadn't gotten around to logging it yet. Should be a pretty simple change.
