### ISSUE TITLE
Mark Items as Collected, But Not Completed

### ISSUE THREAD

**Issue by jlb0170** [kihashi/stardew_community_checklist#72]
I would really like to have a second state for "gathered" but not "completed". I usually have a staging period for most things since I don't like to haul things to the CC as soon as I gather them, I bundle them up in a chest and make a run over there when i can complete a few sets. I've been doing something similar to your site with a spreadsheet, but your site is awesome! This is the only feature missing according to me :)

**Comment by kihashi** [comment]
I've thought about how this would be implemented. Would it make sense to have it click once to mark it as collected (color yellow) and then a second click to mark it as delivered (color green)?

**Comment by jlb0170** [comment]
Yeah, that would be great.

**Comment by jlb0170** [comment]
I briefly tried to implement it but the framework you are using was too magical and I didn't have time to dig into how it worked enough to figure out what I was doing wrong. Sorry about that.

**Comment by kihashi** [comment]
Merging into #83.
