### ISSUE TITLE
Add a Reset Button

### ISSUE THREAD

**Issue by kihashi** [kihashi/stardew_community_checklist#74]
When starting a new game, it would be nice to be able to clear the data without having to mark every item as not collected. It would therefore be useful to have a reset data button with a confirmation dialog.

**Comment by bladeoflight16** [comment]
A simple way to implement this function would be to obtain an export on an empty checklist and invoke the import on it.

**Comment by kihashi** [comment]
@bladeoflight16 Thanks! For reference, I'm currently working on a [full re-write of the application](https://kihashi.github.io/#/welcome). As part of the re-write, I've completely changed how I store data to better accommodate Inventory (#83).

I think the approach that I am taking for the reset is to simply delete the array of stored data. It isn't relying on a specific structure like the live version, so there's no need to re-initialize it.

I appreciate the input, though!
